language: python
python:
- '3.6'
env:
  global:
  - secure: cmS7to7bu1dMoGcpfOYAcOBeeiRUr2AyCAowsz5OOoVq32B9fPG9geyKS1MmM6hC/DG5DEeT0w8GeeZBhhNdUARi5V2cFmDtlzQxDfz/dyvZ7AqmSrSNdi8jdm9UT+za+sWkDuH1IOSywPabvcfNeIIQTKC/VUNJ53BSkacG7JRuT6vcSseqo7wYJdmEJvyf66HxmNg4XlQUz5X9TH6/b9ASEn3QpSg3cQYh7er4MoLSuEmqAIKcfEX/9ijRv05qYS+UkRs7AGAy0YZOFw1K3Byci7mNUlCt5WBZukN+NO0ocThhSFHlN6RiO8F/FkJi52EyY9L8Cd+hORE7b5MEpWm42JgoM9xiodQ/kpyVqf/9Lg1QDiRpyAXD7Z1AZDnVPb92uoPG1OBhro+NJPLkIdIq5dO5zSN/pX5aERXWCdkBHsSmMDKr+LDaeE8S9Cj3znUPbh/aw5sjziHQQ4e1oE3+jRBpIpePbL2jvU806sBZeYOZ1jUzLZMPwJIWtXk628XCdYdZ5uYSuOpRl9nC3Z0dvyIQuirbWQeloichqaSB8v+35AfxW/w/MGguzymGdM5wgvIh2JygHUNf1jByELW2xXGT83uH1VVk/TPrZxrHP3Ham53/uAiH0NCiMLVrIIFJC0r1nKlGvOlixiERBu43KbI2m6qYX2SdcRJkzvE=
  - secure: cHWhmSDPcMFjEdJGi4dZ/hFjN6b1g9nbFxfBGj09X7r5bcGrPd1m7LWpfEOEoWkNodjGAW1tubBlWlUPTC+2YnblayHw2d3Z5SZP2HqNbXazEcoGWCzs9ya4/9l9ENcSdof1SIR9zUzrRXxbjf6891S/eUc8VfZlExKL3pOP0VBu7WfgGYX7u7ahIBjcjTTFTGonsHme5kSFTbsykGS4eBZN2oAXwpSM2LESM/DH70BG6AZs/wbrT6abm78N2HgQdRw4dWr0AFc3W1L/BEw4R5r44ny0EvMdp5Ngsczan25YMzQJxcorgbKgxLDLbI+u/qIDdkOfk6N0jEovIVt30es2Xq3dGvwD6qRZLjFU8OIfljAYjoFeS/bLOH4tGzWxzG3517CBe6kCGuZIGyHh/t3cXHgUbpUobCJ4gG4nmbrQ106g3TKXsg/yPXZi3iWXrlufNhujTgmLjJd73pBBeavG4TdW1cE+UGdQJHKbsvaPtdhfx5QoVqFj8LKDw9eoJmVvSsCJ+utv9ReSHbjoVrRY8VhPe77nH2qAyfU4qY2Puje7DL11QnHevkomNXEfSuzYTN2bzcF7RxsjFyCp7LwYxvUZK4kCE3zBqq/qkRpz7bn+na59QkzsvXLqsok28pxGW3K9kQytnGNtp5l7idD3tDUhqPPM1LLvlzoHg8k=
  - secure: cQqUWzBR4vioXRC+4ExFdzgolw6qy0+rqTAXdNlyuo+7RkvhIx7sxepGOk/4iZvec9cKtLzf6rzIS7Gy2NVVQzkEEpphBvepM4aywUzVLRB03SUjQpGegI6ug4ZDkB/Wilv9PG6yORLmzYx0/tDi7p9nXxhnwQFaWY2xXdvH/dgxgoWa/44BsL5WuTmaj0ypY0ClaZJaNHtqDtvUF6VQHnx4/yxp1J3L/668/wYLERJJsWfb7f7ywiE3ZmwtkQjfNK9zxDq6ccnjL/uKAnFh5rhzbRCp51Or+/DOtihFi/dCaM1+1J1GP9KmYRrlS6eXqxUF8MeMSGAfGyLJ26hU3Gu7o2qgtTr15muvkgMjtwdkDNb+ftgkWh5BJaWN+VZal+uX5kguPbIQe4Hg8obvPEhxd5FUXieBcInmaoI5PFfi/QCmM5WgQDc+7v5E1v7jz8HKNemI+5RfwULe5yIfb2DePtGR87sJy6VClJ7WgYBCEW9+KNSYoTVgnJmpjawbzR9+j2OEsPhf18QPevaXknzujcAAVPr+DXFiMt5KNznLFqaJQLqSbDPIwKzrcgSGufK1OeqjaEEQfGLvKHgVx8YGNeR36uUyib3BVJL5fgur2zQSWZ+yJMqmUseihnMVKR7uMnI9gQbCC2F6d97aNGqQcwK1QBiisZCXwXR3nrQ=
services:
- docker
script: nose2
before_deploy:
- docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- docker build -t himmelseng .
- docker tag himmelseng:latest $DOCKER_HUB_USERNAME/himmelseng:production
- docker push $DOCKER_HUB_USERNAME/himmelseng:production
- openssl aes-256-cbc -K $encrypted_72d0b9165235_key -iv $encrypted_72d0b9165235_iv
  -in deploy_key.enc -out ./deploy_key -d
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i deploy_key root@198.211.127.214 ./deploy.sh
  on:
    branch: V2_Backend
