language: python
python:
    - "3.6"

services:
  - docker

before_install:
- docker build -t himmelseng .

script: nose2

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
    script: echo foo