language: python
python:
- '3.6'

services:
- docker

before_install:
- docker build -t himmelseng .
- docker tag himmelseng:latest $DOCKER_HUB_USERNAME/himmelseng:production
- docker push $DOCKER_HUB_USERNAME/himmelseng:production

script: nose2

env:
  global:
  - secure: C1qrRPrnrVGZ5UQAgs5818Wwyz/ljicUGZE5WjO0l9ECSFsYT7GAtZKw0XWGIsCEeIJ7oto//CxbL5NL/6oZk7L46KHuBKG5SUjb4ElRQBe9c9hsdvCrTC57DgCJmy+5wGhhqDgsoo4/6VGy6Rc3qTpu/6lzdGxogWn+W9qt74OTGS8vOaxnudUj7UWbgPfDWamMFt9cCSgisnPQjUA6AAXC5e+7DTScWEedf2vlsLJQ7pQWk580cvaz7mTcBzoyDeJgS+3KFpqrllSD+e3AjFhwrzdumGJwKXE1ls7CZFkvddN1ccWZ8A0BFtaIv0xNUuD+LvinZMME5VHGR8kWvCv4KsstUINH29Y5kBc7N+XCxZM3IQddofTzkDIZTUckwvk4t7Xh6yZq1wesKYIVEwhtXQY+RxXNIXhILOQ+z+S4Tc72+kQIHukzvqx1oWD0QI8HwPpoo10J0e5zjOrcCsSoId8jiDjr5NJHU86VnOWpGDbxkoTAgTzA0REzzmrD4AxNwcm86FY3+OZqy8zEWqrBojV3hoZlICEpFA2IvIws7Pi+CehNRnQMMCaAuScAnARxjzrcnYEzUqC7T372IuXoKwhgSrBb/8yzIO2aoFnQll9OoZs+mXxN3f4mJmrBbtCLnuRGFAAQMYgAFB3NOVh7i2CcS6rDlgiw39EBWK8=
  - secure: C1CDadzdA69MNfYyr1CvSvqd7ENxD+BPPsbP74ebxqSVt5WnQhZK8i9Nnlhf1Qh4D3vYMIFuIKbsN4qKJj6JruMj1IGJCBr/jfSISt10vc+i/8JgazQvD5dU/UCi855U1Iuj/bBEJXbuRR4tlmEnWhVBQyIQllKNtsJjAD1qvMFM8vke+nO6jfuOdYroSRbVZ36voTOMrXN+zpljh8lpJHVs9K/IXKFpCysuiQbjCjLuRWe9TnwVJvy9oKQqWTP2AzxpIWkfnx2NvBAguxRsSIy8tJdQbGnvxHn1v6TNhm6fssRTZea+wnsJNj+zlIwzNIah4xWsHEkiOv7U83hSJvxxDkC3Yz9Pv5tDHQAPG33aBCBQ9vuRQeGVUMenG9kEfz4EAooWiwrXZR25GqG5xZUiRBJt3ilfYNh2m41IUAvah9F+8g7LnAxuoCRxbjeauXNd4MA/WxmMWzTMBsYPS+ne2BsK3YCeCj43+CIvWcqV3LhwG/J28wdkoGj3O8ne43VfGcmRIQhBVH23vc/M/+fHRGtePEuFUS6viVYVNYdvmHaU2fDs/q57duHfxn8ZAvjDk1tCON3onYVT/yH1PXGyusKJlQRXL92ia0TruXgNOepXyhHbsH58XQb01fXtA7Bko4xZBkr8cVIRBwqZQuaI4yTaJiOB0Wef9A1dl4Q=
  - secure: rUI5ZPivT9Odpk9JseWI1GaJ20imUzYR5ejgy/Y8RsEpHTofpS18QQepZrxrF3PVwb4GIJSf2MWLeecQ9KrYPYZ/Wgfezes8EMjIfNodpsIFbJ2x/m9V4Lm9dgP3jZcaGN6fcg4UXLo3lmoQm17Ze3a3W1t2Cd0y4Zl9D5lKDk0O+cnT6twvqhIKE3hDB15MT5gMvx5mjDU85QCTUylanql2gPefeQNHzJtJMo8MUdH5dSzX4XkrT6j5eP+JVBWy+Gv84IT5hlCVtWnEAKgFJpvs4pzz07e7/+xE+s4UOAlbmcgugoRehIsome/IIjiJ0bGGECgMPNKoCUMH3OEqOQTmGeBuEwm17VNDCLvJ4lmz9SdDmxVTbmlTO5Ye9vZV6JqfIxmwGFYzuGKO/FnpASqboV/hrbQYkMhQwqjgHcsEK13yAJ12WGzH5mjIKfu0+yseo/LD52CRhAKJGYztf9ISWnn/HcZfZv5Sae0jHL2nhqer8XkcXnfYK9AJkfFACb3AAV32QDnh4rgmw/2EFW807jvA1Y+/+3nBU9zmfZ1/nvQ/wKw97qikX8YzEP17fLyKGsUBS8pC8dCHZtOBXG72i7T2dQUKdBjjXUxa/oRfbui1v7w1gZ/0oF5h9bfqAdkl0IXEx651KbxQBt/h+wl74fv4UcgUYXFo+v1Mqt4=
